- name: check_node
  hosts: all
  gather_facts: false
  tasks:
  - name: node_kernel
    shell:
      uname -a
  - name: node_os_version
    shell:
      cat /etc/redhat-release
  - name: node_cpu
    shell:
      vmstat 1 3 | sed -n '$p' | awk '{print ($13+$14)"%"}'
  - name: node_mem
    shell:
      free -m | grep Mem | awk '{print $3/$2*100"%"}'
  - name: node_network_traffic
    shell:
      for i in `seq 1 2`;do
      ifconfig ens192 | egrep "RX packets|TX packets" | awk 'BEGIN{FS=" "}{print $1,$5}'
      [[ $i -eq 1 ]] && sleep 2;
      done | awk '{A[NR]=$2}END{print "RX:"(A[3]-A[1])/10/1024" KB/s","TX:"(A[4]-A[2])/10/1024" KB/s"}'
  - name: node_disk
    shell:
      df -h / | awk 'NR>1{print $5}'
  - name: node_time
    shell:
      date "+%F %T %Z"
  - name: node_load_average
    shell:
      uptime | grep -o load.*
  - name: node_running_time
    shell:
      uptime -p
  - name: node_zombie
    shell:
      p1=$(ps -A -ostat,ppid,pid,cmd | grep -e '^[Zz]');[[ "$p1" ]] && echo $p1 || echo 0
  - name: node_docker
    shell:
      systemctl show -p SubState docker | sed 's/SubState=//g'
  - name: node_current_connection
    shell:
      netstat -ant | grep ESTABLISHED | wc -l
  - name: node_opened_ports_count
    shell:
      netstat -antl | grep LISTEN | wc -l
  - name: node_opened_ports
    shell:
      netstat -antl | grep LISTEN |awk '{print $4}' | awk 'BEGIN{FS=":";RS="\n";ORS=" "}{print $NF}'
  - name: node_opened_process
    shell:
      ps -ef | wc -l
  - name: node_kubelet
    shell:
      systemctl show -p SubState kubelet | sed 's/SubState=//g'
  - name: node_kube_proxy
    shell:
      systemctl show -p SubState kube-proxy | sed 's/SubState=//g'

